---
- name: Create vmail database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: vmail
    state: present
    owner: vmail
    template: template0
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    login_user: postgres
    login_password: password
    login_unix_socket: /run/postgresql
  notify: Create pgcrypto extension

- name: Copy vmail table script to host
  ansible.builtin.copy:
    src: vmail.sql
    dest: /tmp/vmail.sql
    owner: postgres
    group: postgres
    mode: "0600"

- name: Create vmail database tables
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: vmail
    state: restore
    target: /tmp/vmail.sql
    login_user: postgres
    login_password: password
    login_unix_socket: /run/postgresql
