---
- name: Set password for postgres user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: postgres
    password: password
    encrypted: true
    login_user: postgres
    login_password: password
    login_unix_socket: /run/postgresql
  environment:
    PGOPTIONS: -c password_encryption=scram-sha-256

- name: Create vmail database user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: vmail
    state: present
    password: password
    encrypted: true
    login_user: postgres
    login_password: password
    login_unix_socket: /run/postgresql
    role_attr_flags: >-
      NOSUPERUSER,NOCREATEROLE,NOCREATEDB,NOREPLICATION,NOBYPASSRLS
  environment:
    PGOPTIONS: -c password_encryption=scram-sha-256
