---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-pgsql

- name: Import vmail tasks
  ansible.builtin.import_tasks: vmail.yml

- name: Import configure tasks
  ansible.builtin.import_tasks: configure.yml

- name: Enable dovecot service
  ansible.builtin.systemd:
    name: dovecot
    enabled: true
