---
- name: Create vmail group
  ansible.builtin.group:
    name: vmail
    state: present
    gid: 5000
    system: true

- name: Add vmail user account
  ansible.builtin.user:
    name: vmail
    comment: "vmail user"
    shell: /usr/sbin/nologin
    create_home: true
    home: /var/vmail
    system: true
    uid: 5000
    group: vmail
    state: present

- name: Create mail directories
  ansible.builtin.file:
    path: /var/vmail/
    state: directory
    owner: vmail
    group: vmail
    mode: "0770"

- name: Create mail directories
  ansible.builtin.file:
    path: /var/vmail/mailboxes
    state: directory
    owner: vmail
    group: vmail
    mode: "0770"

- name: Run all notified handlers now
  ansible.builtin.meta: flush_handlers
