FROM docker.io/ubuntu:latest

# install dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git \
    golang \
    sudo \
    supervisor \
    postgresql \
    postfix \
    postfix-pgsql \
    dovecot-imapd \
    dovecot-lmtpd \
    dovecot-pgsql \
    && apt-get clean

# copy postgres config files and database sql script
COPY postgres/postgres.conf /etc/postgresql/14/main/conf.d/custom.conf
COPY postgres/pg_hba.conf /etc/postgresql/14/main
COPY postgres/postgres.sql /root

# prepare database
RUN pg_ctlcluster 14/main start \
    && sudo -u postgres psql -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;;" \
    && sudo -u postgres psql -c "CREATE USER vmail with password 'password';" \
    && sudo -u postgres psql -c "CREATE DATABASE vmail;" \
    && sudo -u postgres psql vmail < /root/postgres.sql

# configure postfix
COPY postfix/main.cf /root/main.cf

RUN cat /root/main.cf >> /etc/postfix/main.cf \
    && mkdir /etc/postfix/sql

COPY postfix/master.cf /etc/postfix
COPY postfix/accounts.cf /etc/postfix/sql
COPY postfix/aliases.cf /etc/postfix/sql
COPY postfix/domains.cf /etc/postfix/sql
COPY postfix/sender-login-maps.cf /etc/postfix/sql

# configure dovecot
RUN groupadd -g 5000 vmail \
    && useradd -c "vmail user" -s /usr/sbin/nologin -d /var/vmail -u 5000 -g vmail -m -r vmail \
    && mkdir -p /var/vmail/mailboxes \
    && chown -R vmail:vmail /var/vmail \
    && chmod -R 0770 /var/vmail \
    && rm -rf /etc/dovecot/conf.d /etc/dovecot/dovecot-dict-auth.conf.ext /etc/dovecot/dovecot-dict-sql.conf.ext /etc/dovecot/dovecot-sql.conf.ext

COPY --chown=root:dovecot --chmod=0640 dovecot/dovecot.conf /etc/dovecot
COPY --chown=root:dovecot --chmod=0440 dovecot/dovecot-sql.conf /etc/dovecot

# encrypt mailboxes
ARG PASSWORD=e9a75486736a550af4fea861e2378305c4a555a05094dee1dca2f68afea49cc3a50e8de6ea131ea521311f4d6fb054a146e8282f8e35ff2e6368c1a62e909716

RUN pg_ctlcluster 14/main start \
&& /usr/sbin/dovecot -c /etc/dovecot/dovecot.conf \
&& doveadm -o plugin/mail_crypt_private_password=$PASSWORD mailbox cryptokey generate -u pwch1@localdomain -U \
&& doveadm -o plugin/mail_crypt_private_password=$PASSWORD mailbox cryptokey generate -u pwch2@localdomain -U \
&& doveadm -o plugin/mail_crypt_private_password=$PASSWORD mailbox cryptokey generate -u pwch3@localdomain -U

# symlink doveadm_wrapper
RUN mkdir /pwch \
    && ln -s /pwch/cmd/doveadm_wrapper/doveadm_wrapper /usr/local/bin/doveadm_wrapper

# copy supervisord config
COPY supervisord/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
