FROM docker.io/debian:latest

# install dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git \
    golang \
    sudo \
    supervisor \
    postgresql \
    postfix \
    postfix-pgsql \
    dovecot-imapd \
    dovecot-lmtpd \
    dovecot-pgsql \
    && apt-get clean

# copy postgres config files and database sql script
COPY postgres/postgres.conf /etc/postgresql/15/main/conf.d/custom.conf
COPY postgres/pg_hba.conf /etc/postgresql/15/main
COPY postgres/postgres.sql /root

# prepare database
RUN pg_ctlcluster 15/main start \
    && sudo -u postgres psql -c "CREATE USER vmail with password 'password';" \
    && sudo -u postgres psql -c "CREATE DATABASE vmail;" \
    && sudo -u postgres psql -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;" vmail \
    && sudo -u postgres psql vmail < /root/postgres.sql

# generate certificate
RUN openssl req -x509 -nodes -days 365 -newkey rsa:4096 \
    -keyout /etc/ssl/localhost.key -out /etc/ssl/localhost.crt \
    -subj "/C=US/ST=State/L=City/O=Organization/OU=Unit/CN=localhost" \
    -addext "subjectAltName = DNS:localhost" \
    && cp /etc/ssl/localhost.crt /usr/local/share/ca-certificates/localhost.crt \
    && update-ca-certificates

# configure postfix
COPY postfix/main.cf /root/main.cf

RUN cat /root/main.cf >> /etc/postfix/main.cf \
    && sed -i 's/smtpd_tls_cert_file=.*/smtpd_tls_cert_file=\/etc\/ssl\/localhost.crt/' /etc/postfix/main.cf \
    && sed -i 's/smtpd_tls_key_file=.*/smtpd_tls_key_file=\/etc\/ssl\/localhost.key/' /etc/postfix/main.cf \
    && mkdir /etc/postfix/sql

COPY postfix/master.cf /etc/postfix
COPY postfix/accounts.cf /etc/postfix/sql
COPY postfix/aliases.cf /etc/postfix/sql
COPY postfix/domains.cf /etc/postfix/sql
COPY postfix/sender-login-maps.cf /etc/postfix/sql

# configure dovecot
RUN groupadd -g 5000 vmail \
    && useradd -c "vmail user" -s /usr/sbin/nologin -d /var/vmail -u 5000 -g vmail -m -r vmail \
    && mkdir -p /var/vmail/mailboxes \
    && chown -R vmail:vmail /var/vmail \
    && chmod -R 0770 /var/vmail \
    && rm -rf /etc/dovecot/conf.d /etc/dovecot/dovecot-dict-auth.conf.ext /etc/dovecot/dovecot-dict-sql.conf.ext /etc/dovecot/dovecot-sql.conf.ext

COPY --chown=root:dovecot --chmod=0640 dovecot/dovecot.conf /etc/dovecot
COPY --chown=root:dovecot --chmod=0440 dovecot/dovecot-sql.conf /etc/dovecot

# encrypt mailboxes
ARG PASSWORD1=0cb77f4c044545ffe50dd6637a31ee38a3b5bee453cfc014caa340b8f66b8cf943702b3611ea79131406db8b3bd0c5b473b28f2702fc27f0842d8358f0c25a41
ARG PASSWORD2=c4258232f7fc328b0526681e10f569dfe4c01ff5e21a955fb588d7fc685e55ed25ed57da4770097277faeecba686db8e68fac1ef0fb35076b72d88d1e2d250db
ARG PASSWORD3=b580a7dd415d44c6bc38ab4341a9de9794a278f9ccf9b1cabde5e5ff36d437354167f4877fafd5a02ea2030f96fea2008ca7ba41c95aa05e38e028bba77522d7

RUN pg_ctlcluster 15/main start \
    && /usr/sbin/dovecot -c /etc/dovecot/dovecot.conf \
    && /bin/doveadm -o plugin/mail_crypt_private_password=$PASSWORD1 mailbox cryptokey generate -u pwch1@localdomain -U \
    && /bin/doveadm -o plugin/mail_crypt_private_password=$PASSWORD2 mailbox cryptokey generate -u pwch2@localdomain -U \
    && /bin/doveadm -o plugin/mail_crypt_private_password=$PASSWORD3 mailbox cryptokey generate -u pwch3@localdomain -U

# symlink doveadm_wrapper
RUN mkdir /pwch \
    && ln -s /pwch/cmd/doveadm_wrapper/doveadm_wrapper /usr/local/bin/doveadm_wrapper

# copy supervisord config
COPY supervisord/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
