---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "cmd/pwch"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "cmd/doveadm_wrapper"
    schedule:
      interval: "daily"
