---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "pwch"
    schedule:
      interval: "daily"

- package-ecosystem: "gomod"
    directory: "doveadm_wrapper"
    schedule:
      interval: "daily"
