---
- name: Run CI test
  hosts: all
  gather_facts: false
  roles:
    - role: postgres
      become: true
    - role: postfix
      become: true
    - role: dovecot
      become: true
    - role: pwch
      become: true
    - role: tests
