---
domain: localhost
url_prefix: ""  # e.g. /selfservice
assets_path: /usr/local/src/pwch

server:
  listen_address: 0.0.0.0
  port: 443
  cert_file: /etc/ssl/localhost.crt
  key_file: /etc/ssl/localhost.key

db:
  host: /run/postgresql
  db_name: vmail
  user: vmail
  password: password
  ssl_mode: disable

bcrypt:
  cost: 14  # do NOT change after initial setup

smtp:
  host: localhost
  port: 587
  login_user: noreply@localdomain
  login_password: password
  sender: PWCH <noreply@localdomain>

# these values are used for testing
# these are not sane defaults
password_policy:
  min_length: 8
  max_length: 128
  lower_case: true
  upper_case: false
  digits: false
  special_char: false

otl:
  valid_for: 10m
