---
domain: example.com
url_prefix: /selfservice
assets_path: /usr/local/src/pwch

server:
  socket_path: /run/pwch/pwch.sock

db:
  host: /run/postgresql
  db_name: vmail
  user: vmail
  password: vmail_password
  ssl_mode: disable

bcrypt:
  cost: 14  # do NOT change after initial setup

smtp:
  host: example.com
  port: 587
  login_user: noreply@example.com
  login_password: noreply_password
  sender: PWCH <noreply@example.com

password_policy:
  min_length: 12
  max_length: 128
  lower_case: true
  upper_case: true
  digits: true
  special_char: true

otl:
  valid_for: 10m
