---
pipeline:
  pwch:
    group: build
    image: registry.fedoraproject.org/fedora-minimal:latest
    pull: true
    environment:
      - CGO=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - microdnf install -y --nodocs golang
      - cd cmd/pwch
      - go get
      - go build
      - go install github.com/mattn/goveralls@latest
      - ~/go/bin/goveralls -v -service drone.io

  doveadm_wrapper:
    group: build
    image: registry.fedoraproject.org/fedora-minimal:latest
    pull: true
    environment:
      - CGO=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - microdnf install -y --nodocs golang
      - cd cmd/doveadm_wrapper
      - go build

when:
  event: [push, pull_request]
  branch: main
