---
pipeline:
  pwch:
    group: build
    image: golang
    pull: true
    environment:
      - CGO=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - cd cmd/pwch
      - go get
      - go build

  doveadm_wrapper:
    group: build
    image: golang
    pull: true
    environment:
      - CGO=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - cd cmd/doveadm_wrapper
      - go build

when:
  event: [push, pull_request]
  branch: main
