---
pipeline:
  test_pwch:
    image: localhost/pwch-full:latest
    commands:
      - /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
      - cd cmd/pwch
      - go install github.com/mattn/goveralls@latest
      - goveralls -v -service drone.io
    secrets:
      - coveralls_token

when:
  event: [push, pull_request]
  branch: main
