---
pipeline:
  test_pwch:
    image: localhost/pwch-full:latest
    commands:
      - /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
      - cd /pwch/cmd/pwch
      - go test -v

when:
  event: [push, pull_request]
  branch: main
