---
- name: Add config to main.cf
  ansible.builtin.blockinfile:
    path: /etc/postfix/main.cf
    block: |
      proxy_read_maps = proxy:pgsql:/etc/postfix/sql/aliases.cf
                        proxy:pgsql:/etc/postfix/sql/accounts.cf
                        proxy:pgsql:/etc/postfix/sql/domains.cf
                        proxy:pgsql:/etc/postfix/sql/sender-login-maps.cf

      virtual_alias_maps = proxy:pgsql:/etc/postfix/sql/aliases.cf
      virtual_mailbox_maps = proxy:pgsql:/etc/postfix/sql/accounts.cf
      virtual_mailbox_domains = proxy:pgsql:/etc/postfix/sql/domains.cf
      local_recipient_maps = $virtual_mailbox_maps

      mua_relay_restrictions = permit_mynetworks,permit_sasl_authenticated,reject
      mua_sender_restrictions = permit_mynetworks,permit_sasl_authenticated,reject
      mua_client_restrictions = permit_mynetworks,permit_sasl_authenticated,reject

      virtual_transport = lmtp:unix:private/dovecot-lmtp
  notify: Restart postfix

- name: Copy master.cf config to host
  ansible.builtin.copy:
    src: master.cf
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: "0644"
  notify: Restart postfix

- name: Create sql queries directory
  ansible.builtin.file:
    path: /etc/postfix/sql
    state: directory
    owner: root
    group: postfix
    mode: "0755"

- name: Copy sql query files to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/postfix/sql/{{ item }}
    owner: root
    group: postfix
    mode: "0440"
  notify: Restart postfix
  loop:
    - accounts.cf
    - aliases.cf
    - domains.cf
    - sender-login-maps.cf
