---
name: Go

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install dependencies
        working-directory: cmd/pwch
        run: go get .

      - name: Build pwch
        working-directory: cmd/pwch
        run: go build -v

      - name: Test pwch
        working-directory: cmd/pwch
        run: go test -v

      - name: Build doveadm_wrapper
        working-directory: cmd/doveadm_wrapper
        run: go build -v
